import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IntelliTech Assessement',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-[#F8F9FA]`}>
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  )
}
